---
# handlers file for ocp4-upi-helpernode-role

- name: Restart bind
  service:
    name: named
    state: restarted

- name: Restart haproxy
  service:
    name: haproxy
    state: restarted

- name: Restart httpd
  service:
    name: httpd
    state: restarted

- name: Restart chronyd
  service:
    name: chronyd
    state: restarted

- name: Restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: Restart tftp
  service:
    name: tftp
    state: restarted

- name: Restart nfs
  service:
    name: nfs-server
    state: restarted
